### ISSUE TITLE
Error: ExportOptionsSVG does not have a constructor

### ISSUE THREAD

**Issue by fatihturan** [iconic/illustrator-svg-exporter#15]
Hi,

When I try to export some layers on a .psd file I get an error like this:

![](https://jumpshare.com/v/OmXVDm79C6jPRj7Zw5Hi+/Screen+Shot+2016-02-04+at+2.54.25+PM.png)

You can download the psd and test it from here: http://jmp.sh/TeBQwHi

By the way I used the Photoshop CS5 Extended 12.0.4

Best regards.

**Comment by shaneparsons** [comment]
@fatihturan That's probably because this is an Illustrator plugin – not a Photoshop one.

**Comment by fatihturan** [comment]
Oh shit. How did I miss that. :( Sorry.
