### ISSUE TITLE
When I run the script and select the location nothing outputs

### ISSUE THREAD

**Issue by razster** [iconic/illustrator-svg-exporter#5]
I ran the script (File > Script > Export SVG), selected my location (C:\Temp) and nothing happened.
No errors, nothing.

Running Windows 7 ent, x64.

**Comment by somerandomdude** [comment]
Hey @razster, could you send me the Illustrator file you're trying to export from?

**Comment by razster** [comment]
That shouldn't be an issue - do I send it to your profile email?

**Comment by somerandomdude** [comment]
That would be perfect - thanks!

**Comment by tdurand** [comment]
same here, i work with illustrator cc 2014 on mac os x

**Comment by pmeissner** [comment]
And ditto. Select the folder. Something looks like it's running, but no files are generated.
CC 2014 on Mac OS 10.10.1

**Comment by tazcarper** [comment]
Same problem. Nothing outputs.

Adobe Illustrator CS6 version 16.0.0.
Mac OSX V 10.9.5

**Comment by somerandomdude** [comment]
Wow, OK. This is definitely a thing. So I was able to get a hold of some sample Illustrator files from folks that were having problems. What's weird is that the script worked for me w/ their files. The only difference I could see is that they were using a different language pack. What language is your Illustrator install set to?

**Comment by pmeissner** [comment]
English (North America)

**Comment by somerandomdude** [comment]
Well, that kills that theory... Could you send me your Illustrator file?

**Comment by pmeissner** [comment]
Email sent.

**Comment by somerandomdude** [comment]
OK, so I noticed that none of the paths or layers are given a name to export (for example: circle.svg). The script will only export paths/layers that are given a name with a `.svg` extension at the end. Make that change and see if it works for you.

**Comment by tazcarper** [comment]
English (NA)

**Comment by tazcarper** [comment]
That worked!

**Comment by pmeissner** [comment]
OK. So when I named the AI layer "test.svg" — it works. Thank you.

**Comment by somerandomdude** [comment]
Awesome. @tdurand and @razster, could this be your issue as well?

**Comment by tdurand** [comment]
Worked !

**Comment by somerandomdude** [comment]
OK, I think we're good here. I'm going to close this later today unless @razster is still running into problems.

**Comment by somerandomdude** [comment]
Closing for now. @razster, let me know if it's still breaking for you.

**Comment by razster** [comment]
I will give it a try and let you know.

So I tried it and it did export the file, but something odd is happening, which I guess I will need to make a new bug.

Export issue resolved.
