### ISSUE TITLE
Photoshop Shapes and Paths

### ISSUE THREAD

**Issue by necks** [iconic/illustrator-svg-exporter#6]
I know It might be too much to ask but is it technically possible to make a similar script for exporting PS shapes and paths in a similar way?

**Comment by somerandomdude** [comment]
There isn't a smooth way to export SVGs from Photoshop, although it's definitely been done (see: http://www.layerhero.com/photoshop-svg-exporter/). I think we'd want to wait until Photoshop supports SVG export before making such a script.

**Comment by davidjost** [comment]
Photoshop CC supports svg export, name your layers .svg like you would with generator, then go to file -> extract assets. Obviously only works on shape layers.

**Comment by somerandomdude** [comment]
Apologies - that's correct. By support, I meant ExtendScript support without using Generator. We really like what Generator is up to, but we'd prefer to make a plain-jane script for export. That said, it could definitely be something we take on at a later date.
